.gitignore
app/build.gradle
app/src/main/java/com/example/ohthmhyh/Habit.java
app/src/test/java/com/example/ohthmhyh/HabitUnitTest.java

Initial implementation of the habit class. Also wrote a quick test for the habit class and random habit generator method. Updated .gitignore to ignore some localization files. Modified the app build.gradle to allow for using the LocalDate object on API levels <26 because working with Calendar objects makes me want to cry.
This should satisfy issue #26

implement initial habit class

---

.idea/gradle.xml
.idea/misc.xml
app/build.gradle
app/google-services.json
app/src/main/AndroidManifest.xml
app/src/main/java/com/example/ohthmhyh/LoginActivity.java
app/src/main/java/com/example/ohthmhyh/UserFragment.java
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/fragment_user.xml
build.gradle

Feel free to try and create your own account! Caution: Ugly UI.
Once you sign up, it will take you to the part with the bottom navigation bar. If you go to the user one (the far right button) it will show you your email that you logged in (or signed up) with and also give you the option to sign out.
Right now it only supports logging in and signing up with an email and password. Maybe we need to add username attribute later? I looked into this and it seems we may need a user class first (what @nguyentuthanhdn is working on).
@woodepic, if you wanted to work on this more, please do! Let me know if you have any questions. Oh and if you had time, feel free to start on #30. But no worries if you don't get around to it.
BTW, I used this links to basically do this (if it's any help or just for …

Add basic user login and sign up

---

.idea/misc.xml
app/src/main/res/layout/fragment_user.xml

Still requires tweaking to the UI.
Main functionality needs to be added.

Added the basics of user fragment design

---

app/src/androidTest/java/com/example/ohthmhyh/LoginActivityTest.java
app/src/main/java/com/example/ohthmhyh/LoginActivity.java
app/src/main/res/values/strings.xml

Adds more instrumentation tests for the LoginActivity. This required changing some of the `LoginActivity.java` to use string IDs.
Will address #78.

Add more LoginActivity instrumentation tests

---

app/src/main/java/com/example/ohthmhyh/ApplicationCE.java
app/src/main/java/com/example/ohthmhyh/CERecycleviewAdapter.java
app/src/main/java/com/example/ohthmhyh/CETouchHelp.java
app/src/main/java/com/example/ohthmhyh/CeitemHelpToucherAdapter.java
app/src/main/java/com/example/ohthmhyh/CreateHabitEvent.java
app/src/main/java/com/example/ohthmhyh/CustomAdapterHF.java
app/src/main/java/com/example/ohthmhyh/HabitEventsFragment.java
app/src/main/java/com/example/ohthmhyh/HabitsFragment.java
app/src/main/java/com/example/ohthmhyh/MainActivity.java
app/src/main/java/com/example/ohthmhyh/TouchingHandlingAdaptorHF.java
app/src/main/java/com/example/ohthmhyh/TouchingHandlingHF.java

added some quick java doc and comments

Add more JavaDocs

---

app/src/androidTest/java/com/example/ohthmhyh/DatabaseAdapterTests.java
app/src/androidTest/java/com/example/ohthmhyh/LoginActivityTest.java
app/src/main/java/com/example/ohthmhyh/CustomAdapterHF.java
app/src/main/java/com/example/ohthmhyh/HabitEventList.java
app/src/main/java/com/example/ohthmhyh/HabitList.java
app/src/main/java/com/example/ohthmhyh/HabitsFragment.java
app/src/main/java/com/example/ohthmhyh/LoginActivity.java

Allows for reordering of habits, deleting habits, and adding habits, persistently.
Also sets the username and an initial empty `HabitList` and `HabitEventList` on sign up.

Add username and habit persistence

---

app/build.gradle
app/src/test/java/com/example/ohthmhyh/HabitEventUnitTest.java
app/src/test/java/com/example/ohthmhyh/UserTest.java

This contains unit tests for the user class, and the habit event class

Prior code had a lot of unnecesary complexity. This fixes that.

---

.idea/misc.xml
app/src/androidTest/java/com/example/ohthmhyh/HabitFragmentTest.java
app/src/androidTest/java/com/example/ohthmhyh/UITestHabitFragment.java

I will try to wake up early tomorrow, and add some more, but realistically I don't think I can.

Some UI Tests for adding habit

---

app/src/androidTest/java/com/example/ohthmhyh/Constants.java
app/src/androidTest/java/com/example/ohthmhyh/DatabaseAdapterTests.java
app/src/androidTest/java/com/example/ohthmhyh/HabitFragmentTest.java
app/src/androidTest/java/com/example/ohthmhyh/LoginActivityTest.java

These tests pass on the local machine, but do not in GitHub actions...
Perhaps let's just merge anyway.

Try to fix UI tests

---

.idea/misc.xml
app/src/main/java/com/example/ohthmhyh/CERecycleviewAdapter.java
app/src/main/java/com/example/ohthmhyh/CreateHabitEvent.java
app/src/main/java/com/example/ohthmhyh/HabitEvent.java
app/src/test/java/com/example/ohthmhyh/HabitEventUnitTest.java

habit events now store the location as latitude and longitude. Everything works, but I did not spend a lot of time making it look nice on the habit event fragment as that is currently being refactored by @christianjans anyway.

change location to use lat/lon

---

app/src/androidTest/java/com/example/ohthmhyh/HabitEventsFragmentTest.java
app/src/main/java/com/example/ohthmhyh/CERecycleviewAdapter.java
app/src/main/java/com/example/ohthmhyh/CreateHabitEvent.java
app/src/main/java/com/example/ohthmhyh/HabitEvent.java
app/src/main/java/com/example/ohthmhyh/HabitEventsFragment.java
app/src/main/java/com/example/ohthmhyh/entities/HabitEvent.java
app/src/test/java/com/example/ohthmhyh/HabitEventUnitTest.java

Refactors the HabitEvent class to take in the Habit's UHID instead of an actual Habit object.
Also gets rid of the HabitEvent flag.
Also addresses any errors that come with making this changes.

Refactor the HabitEvent class to take in Habit UHID

---

.idea/misc.xml
app/src/main/res/layout/alert_addhabit.xml

These buttons were also out of order.

Switch Saturday and Sunday buttons

---

app/src/main/java/com/example/ohthmhyh/entities/Habit.java
app/src/main/java/com/example/ohthmhyh/fragments/HabitsTodayFragment.java
app/src/test/java/com/example/ohthmhyh/HabitUnitTest.java

A new Habit method that may help Habits Today stuff.
@woodepic, let me know what you think of these changes.

New Habit method for Habits Today

---

app/src/androidTest/java/com/example/ohthmhyh/DatabaseAdapterTests.java
app/src/androidTest/java/com/example/ohthmhyh/UserDatabaseTests.java
app/src/main/java/com/example/ohthmhyh/FriendRequestListAdapter.java
app/src/main/java/com/example/ohthmhyh/FriendsListAdapter.java
app/src/main/java/com/example/ohthmhyh/activities/LoginActivity.java
app/src/main/java/com/example/ohthmhyh/activities/MainActivity.java
app/src/main/java/com/example/ohthmhyh/activities/UpdateHabitEventActivity.java
app/src/main/java/com/example/ohthmhyh/database/DatabaseAdapter.java
app/src/main/java/com/example/ohthmhyh/database/HabitEventList.java
app/src/main/java/com/example/ohthmhyh/database/HabitList.java
app/src/main/java/com/example/ohthmhyh/entities/User.java
app/src/main/java/com/example/ohthmhyh/fragments/HabitEventsFragment.java
app/src/main/java/com/example/ohthmhyh/fragments/HabitsFragment.java
app/src/main/java/com/example/ohthmhyh/fragments/UserFragment.java

Transforms the DatabaseAdapter into a singleton class.
Step 1 of 2 in trying to create "global" objects for user data.

Make DatabaseAdapter into singleton

---

app/src/main/java/com/example/ohthmhyh/Constants.java
app/src/main/java/com/example/ohthmhyh/activities/UpdateHabitEventActivity.java

Adds a min length and max length constant for the habit event's comment.

Add constants for habit event's comment length

---

app/src/main/java/com/example/ohthmhyh/fragments/UserFragment.java

I previously added methods to allow for deleting friends, but I forgot to add the UI to do it. I have now added a dialog allowing users to remove friends.

allow deleting friends

---

.idea/misc.xml
app/src/main/java/com/example/ohthmhyh/activities/UpdateHabitActivity.java

Make sure the date is not editable when editing a Habit

---

app/src/main/java/com/example/ohthmhyh/Constants.java
app/src/main/java/com/example/ohthmhyh/activities/EditProfileActivity.java
app/src/main/java/com/example/ohthmhyh/activities/LoginActivity.java
app/src/main/java/com/example/ohthmhyh/activities/MainActivity.java
app/src/main/java/com/example/ohthmhyh/activities/MapActivity.java
app/src/main/java/com/example/ohthmhyh/activities/UpdateHabitActivity.java
app/src/main/java/com/example/ohthmhyh/activities/UpdateHabitEventActivity.java
app/src/main/java/com/example/ohthmhyh/adapters/FriendRequestListAdapter.java
app/src/main/java/com/example/ohthmhyh/adapters/FriendsListAdapter.java
app/src/main/java/com/example/ohthmhyh/adapters/HabitEventRecyclerViewAdapter.java
app/src/main/java/com/example/ohthmhyh/adapters/HabitFeedRecyclerViewAdapter.java
app/src/main/java/com/example/ohthmhyh/adapters/HabitRecyclerViewAdapter.java
app/src/main/java/com/example/ohthmhyh/adapters/HabitRecyclerViewGestureAdapter.java
app/src/main/java/com/example/ohthmhyh/adapters/HabitTodayRecyclerViewAdapter.java
app/src/main/java/com/example/ohthmhyh/database/DatabaseAdapter.java
app/src/main/java/com/example/ohthmhyh/database/HabitEventList.java
app/src/main/java/com/example/ohthmhyh/database/HabitList.java
app/src/main/java/com/example/ohthmhyh/entities/Habit.java
app/src/main/java/com/example/ohthmhyh/entities/HabitEvent.java
app/src/main/java/com/example/ohthmhyh/entities/User.java
app/src/main/java/com/example/ohthmhyh/fragments/FeedFragment.java
app/src/main/java/com/example/ohthmhyh/fragments/HabitEventsFragment.java
app/src/main/java/com/example/ohthmhyh/fragments/HabitsFragment.java
app/src/main/java/com/example/ohthmhyh/fragments/HabitsTodayFragment.java
app/src/main/java/com/example/ohthmhyh/fragments/UserFragment.java
app/src/main/java/com/example/ohthmhyh/helpers/TransportableTouchHelper.java
app/src/main/java/com/example/ohthmhyh/interfaces/ItemTransportable.java
app/src/main/java/com/example/ohthmhyh/listeners/DatePickerListener.java
app/src/main/java/com/example/ohthmhyh/listeners/HabitUpdateListener.java
app/src/main/java/com/example/ohthmhyh/watchers/LengthTextWatcher.java

Add introduction comments

---

app/src/main/java/com/example/ohthmhyh/activities/UpdateHabitActivity.java
app/src/main/java/com/example/ohthmhyh/listeners/HabitUpdateListener.java

Updating a Habit would reset its UHID to -1. This prevents that from happening.

Fix updating Habit dereferences HabitEvent

---

.idea/misc.xml
app/src/androidTest/java/com/example/ohthmhyh/HabitTodayFragmentTest.java

All habit today fragment UI tests now work

Fixed the UI tests for habits today
